channels = ["conda-forge"]

[deps]
# Conda package names and versions
python = ">=3.4,<4"
# see https://mne.tools/stable/install/manual_install.html#installing-mne-python-with-all-dependencies
# CondaPkg uses mamba by default
mne = ">=1.4, <2"

[pip.deps]
# mne = ">=1.4"
