channels = ["anaconda", "conda-forge"]

[deps]
# Conda package names and versions
python = ">=3.4,<4"
# see https://mne.tools/stable/install/manual_install.html#installing-mne-python-with-all-dependencies
# CondaPkg uses mamba by default
# currently broken when using conda deps
# xref: https://github.com/beacon-biosignals/PyMNE.jl/issues/17
# xref: https://github.com/cjdoris/PythonCall.jl/issues/315
# mne = ">=1.4"

[pip.deps]
mne = ">=1.4"
