name: YASG-enforcer
on:
  push:
    branches:
      - 'main'
    tags: '*'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    # note: keep in sync with `format/run.jl`
    paths:
      - 'src/**'
      - 'test/**'
      - '.github/workflows/YASG.yml'
      - 'format/**'
jobs:
  format-check:
    name: YASG Enforcement (Julia ${{ matrix.julia-version }} - ${{ github.event_name }})
    # Run on push's or non-draft PRs
    if: (github.event_name == 'push') || (github.event.pull_request.draft == false)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    strategy:
      matrix:
        julia-version: [1.7]
    steps:
      - uses: julia-actions/setup-julia@fa02766e078afaaf09b14210362cee14137e6a32  # v3.0.2
        with:
          version: ${{ matrix.julia-version }}
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Instantiate `format` environment and format
        run: |
          julia --project=format -e 'using Pkg; Pkg.instantiate()'
          julia --project=format 'format/run.jl'
      - uses: reviewdog/action-suggester@2558ba17e65a9039e73764a73009fc05fef28a46 # v1.24.3
        if: github.event_name == 'pull_request'
        with:
          tool_name: JuliaFormatter
          fail_on_error: true
